---
title: "Results"
author: "Carol Liu"
date: "3/22/2022"
output: html_document
---

```{r setup, include=FALSE,warning=F, message=F}
library(ggplot2)
library(dplyr)
library(RColorBrewer)
```


```{r cars}
rd1_res_list <- readRDS("../output/rel_transmission_interim/rd1_res.RDS")
rd2_res_list <- readRDS("../output/rel_transmission_interim/rd2_res.RDS")
rd3_res_list <- readRDS("../output/rel_transmission_interim/rd3_res.RDS")
rd4_res_list <- readRDS("../output/rel_transmission_interim/rd4_res.RDS")

## set data frames for ploting

df <- data.frame(value = c(Reduce(c,rd1_res_list), ## Reduce list of vectors into one vector, combined into column in data frame
                            Reduce(c,rd2_res_list),
                            Reduce(c,rd3_res_list),
                            Reduce(c,rd4_res_list)),
                  round = rep(c("R1 Apr-Jun 20", "R2 Nov 20-Jan 21", "R3 Jun-Aug 21", "R4 Nov-Dec 21"),each = 4000),
                  location = rep(rep(c("All","Home", "Work", "Community"), each = 1000),times=4)) %>%
                  mutate(location = factor(location, levels = c("All", "Home", "Work", "Community")))

```

## Plots
```{r}
ggplot(df, aes(value, fill = round)) + geom_density() +
  geom_density(alpha=0.5) +
  geom_vline(xintercept = 1, col="black", lwd=1, lty=2)+
  facet_wrap(~location, nrow=4)+theme_bw() +
  scale_fill_manual("Round",values = c("#08519C","#3182BD","#6BAED6","#BDD7E7"))+
  
  xlab("Relative transmissability due to contact changes compared to pre-pandemic")+
  ylab("Density") 

```

```{r}
ggplot(df, aes(value, fill = round)) + geom_density()+
  geom_vline(xintercept = 1, col="black", lwd=1, lty=2)+
  geom_density(alpha = 0.4) +
  facet_wrap(~location)+theme_bw() +
  scale_fill_manual("Round",values = rev(brewer.pal(n=4,"Blues")))+
  xlab("Relative transmissability due to contact changes compared to pre-pandemic")+
  ylab("Density") 
```

```{r}
df %>% filter(location == "All") %>%
  ggplot(aes(value, fill = round)) + geom_density(alpha = 0.2) +
  theme_bw() +
  xlab("Prop transmissability due to contact changes compared to pre-pandemic")+
  ggtitle("All locations")
```

```{r}
df %>% filter(location == "Home") %>%
  ggplot(aes(value, fill = round)) + geom_density(alpha = 0.2) +
  theme_bw() +
  xlab("Prop transmissability due to contact changes compared to pre-pandemic")+

    ggtitle("Home")
```

```{r}
df %>% filter(location == "Work") %>%
  ggplot(aes(value, fill = round)) + geom_density(alpha = 0.2) +
  theme_bw() +
  xlab("Prop transmissability due to contact changes compared to pre-pandemic")+
  ggtitle("Work")
```

```{r}
df %>% filter(location == "Community") %>%
  ggplot(aes(value, fill = round)) + geom_density(alpha = 0.2) +
  theme_bw() +
  xlab("Prop transmissability due to contact changes compared to pre-pandemic")+
  ggtitle("Other community locations")
```

